import Head from 'next/head'
import { Inter, Alex_Brush } from 'next/font/google'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'next-i18next'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  
  const { t } = useTranslation()
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className=''>
      <h1 className='text-6xl text-green-600'>{t("HELLO_WORLD")}</h1>
      </section>
    </>
  )
}
export async function getStaticProps(context) {
  
  const { locale } = context

  return {
    props: {
      
      ...(await serverSideTranslations(locale)),
    },
  }
}
